name: linux
on:
  push:
    paths-ignore:
      - "LICENSE"
      - "README.md"
      - "version.txt"
      - ".github/workflows/windows*.yml"
      - ".github/workflows/macos*.yml"
  pull_request:
    paths-ignore:
      - "LICENSE"
      - "README.md"
      - "version.txt"
      - ".github/workflows/windows*.yml"
      - ".github/workflows/macos*.yml"
  workflow_dispatch:

jobs:
  build_package_upload:
    timeout-minutes: 60
    env:
      APP_NAME: BesLyric-for-X

      // GLIBC 2.27 supported: https://github.com/probonopd/linuxdeployqt/commit/a3648aed4ad98bf91d087135a92d08806e52e291
      LINUXDEPLOYQT_URL: "https://github.com/probonopd/linuxdeployqt/releases/download/8/linuxdeployqt-continuous-x86_64.AppImage"

      MAKE_INSTALL_DIR_PATH: ${{ github.workspace }}/${{ github.run_id }}/build
      PACKAGE_DIR_PATH: ${{ github.workspace }}/${{ github.run_id }}/package

      LINUXDEPLOYQT_PATH: "${{ github.workspace }}/linuxdeployqt.AppImage"

    runs-on: ubuntu-18.04
    continue-on-error: false
    strategy:
      matrix:
        qt_ver: [5.15.2]
    steps:
      - name: What time?
        id: my_luminous_watch
        uses: josStorer/get-current-time@v2.0.2
        with:
          format: "YYYYMMDDHHmmss"

      # TODO: Don't fetch all history for all tags and branches.
      - uses: actions/checkout@v3.2.0
        with:
          fetch-depth: 0

      - name: Fetch macOS submodules
        if: ${{ runner.os == 'macOS' }}
        run: git submodule update --init --depth=1 --recursive -- .deploy-package/macOS
      - name: Fetch Linux submodules
        if: ${{ runner.os == 'Linux' }}
        run: git submodule update --init --depth=1 --recursive -- .deploy-package/Linux
      - name: Fetch Windows submodules
        if: ${{ runner.os == 'Windows' }}
        run: git submodule update --init --depth=1 --recursive -- .deploy-package/Windows

      # TODO: use GHA stuff, don't write those code.
      - name: Get commit SHA1 and version number from git
        id: getGitInfo
        run: |
          set -o pipefail

          gitCommitSha1=$(git rev-parse HEAD)
          versionNumber=$(git describe --tags --abbrev=0 | \
            egrep --only-matching '[0-9]+\.[0-9]+\.[0-9]+')
          # Note:
          #   1. '[0-9]' is not equivalent to '\d' in all implementations.
          #   2. GNU grep -E / egrep does not support '\d':
          #     https://stackoverflow.com/questions/3185457/pattern-matching-digits-does-not-work-in-egrep
          #     https://stackoverflow.com/questions/6901171/is-d-not-supported-by-greps-basic-expressions

          echo "gitCommitSha1 = ${gitCommitSha1}"
          echo "versionNumber = ${versionNumber}"

          echo "gitCommitSha1=${gitCommitSha1}" >>$GITHUB_OUTPUT
          echo "versionNumber=${versionNumber}" >>$GITHUB_OUTPUT

      - name: Create directories
        run: |
          mkdir -p '${{ env.MAKE_INSTALL_DIR_PATH }}'
          mkdir -p '${{ env.PACKAGE_DIR_PATH }}'

      - run: |
          sudo apt-get update

      - name: apt install 3rd party libs
        run: |
          # https://doc.qt.io/qt-5/linux.html#debian-ubuntu-apt-get
          sudo apt install --no-install-recommends -y libgl1-mesa-dev

          sudo apt install --no-install-recommends -y libsdl2-dev

          sudo add-apt-repository -y ppa:savoury1/ffmpeg4
          sudo apt-get update
          sudo apt install --no-install-recommends -y \
            libavcodec-dev \
            libavformat-dev \
            libavutil-dev \
            libswresample-dev \
            ffmpeg

      - name: Install Qt
        uses: jurplel/install-qt-action@v3.0.0
        with:
          version: ${{ matrix.qt_ver }}
          target: desktop
          cache: true

      - name: Find Qt 5
        if: ${{ startsWith(matrix.qt_ver, '5') }}
        run: |
          echo 'Qt5_DIR = ${{ env.Qt5_DIR }}'
          echo 'Qt_DIR=${{ env.Qt5_DIR }}' >>$GITHUB_ENV

      - name: Find Qt 6
        if: ${{ startsWith(matrix.qt_ver, '6') }}
        run: |
          echo 'Qt6_DIR = ${{ env.Qt6_DIR }}'
          echo 'Qt_DIR=${{ env.Qt6_DIR }}' >>$GITHUB_ENV

      - name: Configure Qt env
        run: |
          echo '${{ env.Qt_DIR }}/bin' >>$GITHUB_PATH

      - name: Test Qt & env
        run: |
          echo ${PATH}

          which 'cmake'

          cmake '--version'

      - name: Build ${{ steps.getGitInfo.outputs.versionNumber }}+${{ steps.getGitInfo.outputs.gitCommitSha1 }}
        run: |
          cmake \
            -D 'CMAKE_BUILD_TYPE=RelWithDebInfo' \
            -D 'CMAKE_PREFIX_PATH=${{ env.Qt_DIR }}' \
            -D 'CMAKE_INSTALL_PREFIX=${{ env.MAKE_INSTALL_DIR_PATH }}' \
            -D 'GIT_COMMIT_SHA1=${{ steps.getGitInfo.outputs.gitCommitSha1 }}' \
            -D 'APP_VERSION=${{ steps.getGitInfo.outputs.versionNumber }}' \
            -S '${{ github.workspace }}' \
            -B '${{ github.workspace }}/build'

          cmake \
            --build '${{ github.workspace }}/build' \
            -j $(nproc) \
            --target install

          du -ach '${{ env.MAKE_INSTALL_DIR_PATH }}'

      - name: Prepare for deployment and packaging
        run: |
          # XCB stuff
          #   ldd .../plugins/platforms/libqxcb.so
          #   also, see https://github.com/jurplel/install-qt-action/issues/88
          sudo apt install --no-install-recommends -y \
            libxcb-dri2-0 \
            libxcb-dri3-0 \
            libxcb-glx0 \
            libxcb-icccm4 \
            libxcb-image0 \
            libxcb-keysyms1 \
            libxcb-present0 \
            libxcb-randr0 \
            libxcb-render0 \
            libxcb-render-util0 \
            libxcb-shape0 \
            libxcb-shm0 \
            libxcb1 \
            libxcb-sync1 \
            libxcb-util1 \
            libxcb-xfixes0 \
            libxcb-xinerama0 \
            libxcb-xkb1

          wget '${{ env.LINUXDEPLOYQT_URL }}' -O '${{ env.LINUXDEPLOYQT_PATH }}'
          chmod u+x '${{ env.LINUXDEPLOYQT_PATH }}'

      - name: Deploy and package
        run: |
          pushd '${{ env.PACKAGE_DIR_PATH }}'

          DESKTOP_FILE_PATH='${{ env.MAKE_INSTALL_DIR_PATH }}/usr/share/applications/BesLyric-for-X.desktop' \
          LINUXDEPLOYQT_PATH='${{ env.LINUXDEPLOYQT_PATH }}' \
          QMAKE_PATH='${{ env.Qt_DIR }}/bin/qmake' \
          VERSION='${{ steps.getGitInfo.outputs.versionNumber }}' \
            bash '${{ github.workspace }}/.deploy-package/Linux/call_linuxdeployqt.sh'

          popd

      - name: Upload AppImage
        uses: actions/upload-artifact@v3.1.1
        with:
          if-no-files-found: error
          name: "${{ steps.my_luminous_watch.outputs.formattedTime }}-Linux-${{ matrix.qt_ver }}-AppImage"
          path: "${{ env.PACKAGE_DIR_PATH }}/${{ env.APP_NAME }}-${{ steps.getGitInfo.outputs.versionNumber }}-x86_64.AppImage"
